# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage "https://www.42nerds.com"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/42nerds/42nerdsctl/releases/download/v0.1.2/42nerdsctl_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "bfc016a775c962273e84d093f2e23da3a6fbddf17600059aaef73da4d09bc804"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/42nerds/42nerdsctl/releases/download/v0.1.2/42nerdsctl_0.1.2_Linux_x86_64.tar.gz"
      sha256 "faaf2018fdd84758033b8e7949f3667f68dafe03be4e2b21c73f051d8e04e7d9"
    end
  end

  def install
    bin.install "42nerdsctl"
  end
end
